@startuml
!theme vibrant
class Player {
  int money
  int bet_size
  vector<Card> cards
  void hit()
  void stand()
  void take_insurance()
  void double_down()
  bool has_insurance
  int get_points()
  bool is_broke()
  bool check_if_over_21()
  int check_if_less_than_dealer()
  void win()
  void lose()
}
  
class Card {
  char color
  int value
}

class GameController{
  int number_players /' needed for logic '/
  vector<Player> players
  int turn
  int round
  int dealer_points
  int min_bet
  void next_turn()
  void start_round()
  void check_winner()
  void start_game() /' '/
  void end_game()
  int compute_dealers_points()
  Shoe shoe
}

class Shoe{
  vector<Card> cards
  Card pop_card() 
  void shuffle_cards()
}

Shoe "1" *-- "many" Card 


GameController "1" - "many" Player 

GameController - Shoe
@enduml
