@startuml
' !theme plain
!theme vibrant

class Player {
  money: int
  bet_size: int
  cards: vector<Card> 
  hit(): void
  stand(): void
  take_insurance(): void
  double_down(): void
  has_insurance: bool
  has_doubled_down: bool
  get_points(): int
  is_broke(): bool
  check_if_over_21(): bool
  check_if_less_than_dealer(): int
  win_round(): void
  lose_round(): void
  player_name: string
}
  
class Card {
  suit: char
  value: int
  point_value: int
}

class GameState{
  max_number_players: int, set to 5
  max_number_rounds: int, set to 100
  number_players: int
  players: vector<Player>
  turn: int
  round: int
  dealer_hand: vector<Card>
  min_bet: int
  next_turn(): void
  start_round(): void
  check_winner(): void
  compute_dealers_hand(): vector<Card>
  shoe: Shoe
  show_first_card(): void()
}

class Shoe{
  cards: vector<Card> 
  pop_card(): Card
  shuffle_cards(): void
}

Shoe "1" *-- "many" Card 


GameState "1" - "many" Player 

GameState - Shoe
@enduml
