@startuml
actor Bob
activate GameState

Bob -> GameControl: press 'stand'
activate GameControl

GameControl -> GameState: stand
deactivate GameControl

alt opt turn == num_players - 1
  GameState -> GameState: compute_dealers_hand

  GameState -> Player: check_winner
  activate Player

  alt Player wins Round

    Player -> GameState: win_round

  else Player loses Round

    Player -> Player: lose_round

    Player -> game_instance: is_broke
    deactivate Player
    activate game_instance

    alt Player is broke

      game_instance -> GameControl: try_remove_player
      activate GameControl
      GameControl -> Bob: showGameOverMessage
      deactivate GameControl

    else Player is not broke
    end
  end

  alt Round = Max_Round - 1

  game_instance -> Bob: showGameOverMessage

  else Not Last Round

  game_instance -> Bob: showNewRoundMessage
  deactivate game_instance

  Bob -> GameState: press 'continue' \n (through Requesthandler)

  GameState -> GameState: next_round

  end

else Not last turn

  GameState -> GameState: next turn

end
