@startuml
actor Player_1 as player

player -> GameControl: press 'connect'
activate GameControl

GameControl -> ClientNetworkManager: sendRequest()
activate ClientNetworkManager

ClientNetworkManager -> server_network_manager: join_game_request\nover network
deactivate ClientNetworkManager
deactivate GameControl
activate server_network_manager

server_network_manager -> request_handler: handle_request()
activate request_handler

request_handler -> player_manager: add_player()
activate player_manager

player_manager --> request_handler: success
deactivate player_manager

group opt [success == True]
  request_handler -> game_instance: add_player()
  activate game_instance

  game_instance -> server_network_manager: broadcast_message()
  deactivate game_instance
  activate server_network_manager

  group par [for all other players in lobby]
    server_network_manager -> ClientNetworkManager: change_gamestate_msg\nvia network
    deactivate server_network_manager
    activate ClientNetworkManager

    ClientNetworkManager -> GameControl: updateGameState()
    activate GameControl

    GameControl -> player: show updated lobby
    deactivate GameControl
    deactivate ClientNetworkManager
  end
end

request_handler --> server_network_manager: response
deactivate request_handler

server_network_manager -> ClientNetworkManager: answer_rqst_response\nvia network
deactivate server_network_manager
activate ClientNetworkManager

ClientNetworkManager -> GameControl: updateGameState()
activate GameControl

GameControl -> player: show lobby or message
deactivate GameControl
deactivate ClientNetworkManager
